name: Trigger Jenkins Job
description: QA 팀의 자동화 테스트를 실행시킵니다.

inputs:
  jenkins_url:
    description: 'Jenkins 서버 URL'
    required: true
  jenkins_user:
    description: 'Jenkins 사용자 이름'
    required: true
  jenkins_token:
    description: 'Jenkins API 토큰'
    required: true

runs:
  using: "composite"
  steps:
    - name: Trigger Jenkins Job
      shell: bash
      run: |
        echo "Triggering Jenkins..."
        curl -X POST -L \
          --user "${{ inputs.jenkins_user }}:${{ inputs.jenkins_token }}" \
          "${{ inputs.jenkins_url }}/job/Neubie-go/build"