name: Selective Build

on:
  pull_request:
    branches:
      - main
      - dev
      - staging

jobs:
  detect-affected:
    runs-on: ubuntu-latest
    outputs:
      affected_apps: ${{ steps.get.outputs.apps }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: yarn install

      - name: Get affected apps
        id: get
        run: |
          BASE=${{ github.event.pull_request.base.ref }}
          HEAD=$(git rev-parse HEAD)
          echo "Comparing from $BASE to $HEAD"
          apps=$(yarn nx show projects --affected --base=origin/$BASE --head=$HEAD | tr -d '\r' | tr ' ' '\n' | grep -E "^(app1|app2)$" | paste -sd ',' -)
          echo "apps=$apps"
          echo "apps=$apps" >> $GITHUB_OUTPUT

  build:
    needs: detect-affected
    runs-on: ubuntu-latest
    if: ${{ needs.detect-affected.outputs.affected_apps != '' }}
    strategy:
      matrix:
        app: [app1, app2]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run build steps if app is affected
        if: contains(needs.detect-affected.outputs.affected_apps, matrix.app)
        run: |
          echo "Running steps for affected app: ${{ matrix.app }}"
          yarn install
          yarn nx build ${{ matrix.app }}