name: Trigger Jenkins Job

on:
  workflow_dispatch:


jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins Job on Repo A
        uses: toptal/jenkins-job-trigger-action@master
        with:
          jenkins_url: ${{ secrets.JENKINS_URL }}   # http 포함된 전체 주소
          jenkins_user: ${{ secrets.JENKINS_USER }}
          jenkins_token: ${{ secrets.JENKINS_TOKEN }}
          job_name: Neubie-go  # 트리거할 Jenkins Job 이름
