name: Trigger Jenkins Job

on:
  workflow_dispatch:


jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins Job on Repo A
        env:
          JENKINS_USER: ${{ secrets.JENKINS_USER }}
          JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
          JENKINS_URL: ${{ secrets.JENKINS_URL }}   # http 포함된 전체 주소
          JOB_NAME: Neubie-go  # 트리거할 Jenkins Job 이름
          BUILD_TOKEN: ${{ secrets.JENKINS_NEUBIE_GO_BUILD_TOKEN }}  # Jenkins Job 설정에서 등록한 토큰
        run: |
          echo "Fetching crumb..."
          CRUMB=$(curl -s -u "$JENKINS_USER:$JENKINS_TOKEN" "$JENKINS_URL/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,\":\",//crumb)")
          echo "$CRUB"
          echo "$JENKINS_USER:$JENKINS_TOKEN"
          echo "Triggering Jenkins job..."
          curl -X POST \
            -u "$JENKINS_USER:$JENKINS_TOKEN" \
            -H "$CRUMB" \
            "${{ secrets.JENKINS_URL }}/build?token=${{ secrets.JENKINS_NEUBIE_GO_BUILD_TOKEN }}"