name: Deploy to Vercel

on:
  workflow_dispatch:
    inputs:
      app:
        description: "Select app to be deployed"
        required: true
        default: "app1"
        type: choice
        options:
          - APP1
          - APP2

jobs:
  deploy:
    if: github.ref_name == 'main' || github.ref_name == 'staging'
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets[format('VERCEL_PROJECT_ ID_{0}', github.event.inputs.app)]}}

    steps:
      - uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: |
          echo "${{ secrets[format('VERCEL_PROJECT_ ID_{0}', github.event.inputs.app)]}}"
          if [ "${{ github.ref_name }}" == "main" ]; then
            vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          else
            vercel pull --yes --environment=preview --git-branch=staging --token=${{ secrets.VERCEL_TOKEN }}
          fi


      - name: Build Project Artifacts
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
          else
            vercel build --token=${{ secrets.VERCEL_TOKEN }}
          fi

      - name: Deploy Project Artifacts to Vercel
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
          else
            vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
          fi
