name: Deploy to Vercel

on:
  workflow_dispatch:
    inputs:
      app1:
        description: "Select app1"
        required: false
        type: boolean
      app2:
        description: "Select app2"
        required: false
        type: boolean

      environment:
        description: "Select deployment environment"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: ${{ fromJson('["app1", "app2"]') }}

    steps:
      - uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}



      - name: Build and Deploy for Selected Apps
        run: |
          apps=()
          if [ "${{ github.event.inputs.app1 }}" == "true" ]; then
            apps+=("app1")
          fi
          if [ "${{ github.event.inputs.app2 }}" == "true" ]; then
            apps+=("app2")
          fi
          
          for app in "${apps[@]}"; do
            echo "Deploying $app"
          
            # Build Project Artifacts
            if [ "${{ github.event.inputs.environment }}" == "main" ]; then
              vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
            else
              vercel build --token=${{ secrets.VERCEL_TOKEN }}
            fi
          
            # Deploy Project Artifacts to Vercel
            if [ "${{ github.event.inputs.environment }}" == "main" ]; then
              vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
            else
              vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
            fi
