name: Deploy to Vercel
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

on:
  workflow_dispatch:
    inputs:
      app1:
        description: "Select app1"
        required: false
        type: boolean
      app2:
        description: "Select app2"
        required: false
        type: boolean

      environment:
        description: "Select deployment environment"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Set up deployment environment
        id: setup_env
        run: |
          apps=()
          if [ "${{ github.event.inputs.app1 }}" == "true" ]; then
            apps+=("app1")
          fi
          if [ "${{ github.event.inputs.app2 }}" == "true" ]; then
            apps+=("app2")
          fi
          echo "selected_apps=${apps[@]}" >> $GITHUB_ENV

      - name: Pull Vercel Environment Information
        run: |
          if [ "${{ github.event.inputs.environment }}" == "main" ]; then
            vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          else
            vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
          fi

      - name: Build and Deploy for Selected Apps
        run: |
          for app in ${{ env.selected_apps }}; do
            echo "Deploying $app"

            # Set Project ID based on app
            if [ "$app" == "app1" ]; then
              export VERCEL_PROJECT_ID="${{ secrets.VERCEL_PROJECT_ID_APP1 }}"
            elif [ "$app" == "app2" ]; then
              export VERCEL_PROJECT_ID="${{ secrets.VERCEL_PROJECT_ID_APP2 }}"
            fi
            echo "Using Project ID: $VERCEL_PROJECT_ID"

            # Build Project Artifacts
            if [ "${{ github.event.inputs.environment }}" == "main" ]; then
              vercel build --prod --token=${{ secrets.VERCEL_TOKEN }} --project-id=$VERCEL_PROJECT_ID
            else
              vercel build --token=${{ secrets.VERCEL_TOKEN }} --project-id=$VERCEL_PROJECT_ID
            fi

            # Deploy Project Artifacts to Vercel
            if [ "${{ github.event.inputs.environment }}" == "main" ]; then
              vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} --project-id=$VERCEL_PROJECT_ID
            else
              vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} --project-id=$VERCEL_PROJECT_ID
            fi
          done