name: Build & Deploy Affected Apps

on:
  merge_group:
    branches: [main, dev]

jobs:
  detect-affected:
    runs-on: ubuntu-latest
    outputs:
      affected: ${{ steps.set.outputs.apps }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: yarn install

      - name: Detect affected apps
        id: set
        run: |
          BASE=${{ github.event.pull_request.base.ref }}
          APPS=$(yarn nx show projects --affected --base=origin/$BASE --head=HEAD | tr ' ' '\n' | grep -E "^(app1|app2)$" | tr '\n' ',' | sed 's/,$//')
          echo "apps=$APPS"
          echo "apps=$APPS" >> $GITHUB_OUTPUT

  build-and-deploy:
    needs: detect-affected
    if: ${{ needs.detect-affected.outputs.affected != '' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [app1, app2]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: yarn install

      - name: Check if app is affected
        id: check
        run: |
          echo "affected=${{ needs.detect-affected.outputs.affected }}" > affected.txt
          if grep -qw "${{ matrix.app }}" affected.txt; then
            echo "should_deploy=true" >> $GITHUB_OUTPUT
          else
            echo "should_deploy=false" >> $GITHUB_OUTPUT
          fi

      - name: Build app
        if: steps.check.outputs.should_deploy == 'true'
        run: yarn nx build ${{ matrix.app }}

      - name: Deploy to Vercel
        if: steps.check.outputs.should_deploy == 'true'
        run: |
          npm install -g vercel@latest
          APP_DIR="apps/${{ matrix.app }}"
          PROJECT_ID_VAR="VERCEL_PROJECT_ID_$(echo '${{ matrix.app }}' | tr '[:lower:]-' '[:upper:]_')"
          PROJECT_ID=${{ secrets[format('VERCEL_PROJECT_ID_{0}', matrix.app) ] }}

          echo "Deploying ${{ matrix.app }} to Vercel"

          vercel deploy --cwd $APP_DIR \
            --token ${{ secrets.VERCEL_TOKEN }} \
            --org ${{ secrets.VERCEL_ORG_ID }} \
            --project $PROJECT_ID \
            --prod \
            --yes